In [1]:
from spin_lattices import SquareLattice, SpinLattice, ParallelogramSpinLattice
from heisenberg_hamiltonians import HeisenbergJ1J2, SpinSystem
import torch
import torch.nn as nn
import torch.nn.functional as F
from conv2d_circular import CircularPad2d
import numpy as np

In [24]:
lattice = SquareLattice(6, 4)
system = HeisenbergJ1J2(
    lattice, J1=1, J2=0.5, use_symmetries=True, spin_inversion=1, skip_symmetries_whitelist=True
)

2023-10-24 18:03:17.404 | DEBUG    | heisenberg_hamiltonians:__init__:472 - number_spins=24
2023-10-24 18:03:17.437 | DEBUG    | heisenberg_hamiltonians:__init__:482 - Symmetry group contains 96 elements
2023-10-24 18:03:17.438 | DEBUG    | heisenberg_hamiltonians:__init__:483 - Constructing basis


2023-10-24 18:03:17.542 | DEBUG    | heisenberg_hamiltonians:__init__:491 - Hilbert space dimension is 15578


In [25]:
system.get_eigenstates(1)

2023-10-24 18:03:19.444 | DEBUG    | heisenberg_hamiltonians:_find_cached_eigenstate:69 - Using cached version of eigenvalues / eigenstates from groundstates/HeisenbergJ1J2-SquareLattice6x4-1.0-0.5-True-1-1.pickle
2023-10-24 18:03:19.466 | DEBUG    | heisenberg_hamiltonians:get_eigenstates:117 - Ground state energy is -50.1623937953


(array([-50.1623938]),
 array([[ 2.24339311e-07],
        [-6.27220766e-07],
        [ 1.56778183e-07],
        ...,
        [ 9.45689145e-02],
        [ 1.36998380e-01],
        [ 8.95276681e-02]]))

In [5]:
# input_width = 3
# input_height = 4
# x = torch.from_numpy(
#     np.array(
#         [
#             np.arange(input_width * input_height).reshape(input_height, input_width),
#             np.arange(input_width * input_height).reshape(input_height, input_width) * 10,
#         ]
#     ).astype(np.float32)
# ).reshape(1, 2, input_height, input_width)
# kernel_size = 3
# dilation = 5
# reception_field = kernel_size + (kernel_size - 1) * (dilation - 1)
# nn.Conv2d(2, 3, kernel_size=kernel_size, dilation=dilation, padding=0)(
#     circular_pad(x, (reception_field - 1, reception_field - 1))
# ).shape

In [27]:
net = InvariantSpinCNNRegression(lattice=lattice, hidden_channels=[32, 32, 32], dilations=[2, 3, 40])

In [28]:
net(torch.from_numpy(system.basis.states.astype(np.int64)))

tensor([[-0.1578],
        [-0.1577],
        [-0.1572],
        ...,
        [-0.1584],
        [-0.1587],
        [-0.1550]], grad_fn=<AddmmBackward0>)