In [1]:
import datetime

In [11]:
# parse the date 2024-04-28 18:32:41.489
date_end = datetime.datetime.strptime("2024-04-28 18:32:41.489", "%Y-%m-%d %H:%M:%S.%f")
date_start = datetime.datetime.strptime("2024-04-26 21:34:19.340", "%Y-%m-%d %H:%M:%S.%f")
time_delta = date_end - date_start
# print formatted time_delta
print(time_delta)
print(time_delta / 200000 * 50000)

1 day, 20:58:22.149000
11:14:35.550000


In [43]:
import lattice_symmetries as ls
from sympy.combinatorics import Permutation
from sympy import Rational
from itertools import combinations

In [58]:
e = ls.Expr("σ⁺₀ σ⁻₁ + σ⁺₁ σ⁻₀", sites=[(0, 1), (1, 2), (2, 3), (3, 0), (0, 2), (1, 3)])

In [63]:
def check_consistency(symmetries: list[tuple[Permutation, Rational]]):
    for (p1, r1), (p2, r2) in combinations(symmetries, 2):
        p = p1 * p2
        r = (r1 + r2) % 1
        for q, s in symmetries:
            if p == q and r != s:
                print(f"{p1} * {p2} = {p} != {q} = {q} => {r1} + {r2} = {r} != {s} = {s}")
                return False
            if p == q and r == s:
                print(f"OK: {p1} * {p2} = {p} = {q} = {q} => {r1} + {r2} = {r} = {s} = {s}")
    return True

In [65]:
for symmetry in e.hilbert_space_sectors():
    assert check_consistency(symmetry.symmetries)

OK: (3) * (2 3) = (2 3) = (2 3) = (2 3) => 0 + 0 = 0 = 0 = 0
OK: (3) * (3)(0 1) = (3)(0 1) = (3)(0 1) = (3)(0 1) => 0 + 0 = 0 = 0 = 0
OK: (3) * (0 1)(2 3) = (0 1)(2 3) = (0 1)(2 3) = (0 1)(2 3) => 0 + 0 = 0 = 0 = 0
OK: (2 3) * (3)(0 1) = (0 1)(2 3) = (0 1)(2 3) = (0 1)(2 3) => 0 + 0 = 0 = 0 = 0
OK: (2 3) * (0 1)(2 3) = (3)(0 1) = (3)(0 1) = (3)(0 1) => 0 + 0 = 0 = 0 = 0
OK: (3)(0 1) * (0 1)(2 3) = (2 3) = (2 3) = (2 3) => 0 + 0 = 0 = 0 = 0
OK: (3) * (2 3) = (2 3) = (2 3) = (2 3) => 0 + 1/2 = 1/2 = 1/2 = 1/2
OK: (3) * (3)(0 1) = (3)(0 1) = (3)(0 1) = (3)(0 1) => 0 + 0 = 0 = 0 = 0
OK: (3) * (0 1)(2 3) = (0 1)(2 3) = (0 1)(2 3) = (0 1)(2 3) => 0 + 1/2 = 1/2 = 1/2 = 1/2
OK: (2 3) * (3)(0 1) = (0 1)(2 3) = (0 1)(2 3) = (0 1)(2 3) => 1/2 + 0 = 1/2 = 1/2 = 1/2
OK: (2 3) * (0 1)(2 3) = (3)(0 1) = (3)(0 1) = (3)(0 1) => 1/2 + 1/2 = 0 = 0 = 0
OK: (3)(0 1) * (0 1)(2 3) = (2 3) = (2 3) = (2 3) => 0 + 1/2 = 1/2 = 1/2 = 1/2
OK: (3) * (2 3) = (2 3) = (2 3) = (2 3) => 0 + 1/2 = 1/2 = 1/2 = 1/2
OK: (3)

In [44]:
Rational(1, 2) + Rational(3, 4)

5/4

In [4]:
from sympy.combinatorics import Permutation
from sympy import Rational
import json

In [5]:
json.dumps({0: Permutation([0, 3, 2, 1])})

TypeError: Object of type Permutation is not JSON serializable

In [1]:
import lattice_symmetries as ls

In [4]:
basis = ls.SpinBasis(number_spins=2)

In [10]:
basis._payload.info.hamming_weight

-1

In [4]:
csr_matrix((M.data, M.indices, M.indptr), shape=(2, -1))

ValueError: 'shape' elements cannot be negative

In [22]:
import numpy as np
import pdb, traceback, sys


In [2]:
np.array([]).__array_interface__

{'data': (21146208, False),
 'strides': None,
 'descr': [('', '<f8')],
 'typestr': '<f8',
 'shape': (0,),
 'version': 3}

In [26]:
class TestArray:
    def __init__(self):
        self.__array_interface__ = {
            "data": (0, True),
            "strides": None,
            "descr": [("", "<f8")],
            "typestr": "<f8",
            "shape": (0,),
            "version": 3,
        }

In [27]:
np.array(TestArray())

TypeError: float() argument must be a string or a real number, not 'TestArray'

In [25]:
import sys, numpy; print(numpy.__version__); print(sys.version)

1.26.1
3.11.6 (main, Oct  2 2023, 13:45:54) [GCC 12.3.0]


In [23]:
try:
    np.array(TestArray())
except:
    extype, value, tb = sys.exc_info()
    traceback.print_exc()
    pdb.post_mortem(tb)


Traceback (most recent call last):
  File "/scratch-local/ishchurov.5569236/nix-shell.Yf1h9D/ipykernel_1227777/1329458018.py", line 2, in <module>
    np.array(TestArray())
TypeError: float() argument must be a string or a real number, not 'TestArray'


> /scratch-local/ishchurov.5569236/nix-shell.Yf1h9D/ipykernel_1227777/1329458018.py(2)<module>()
      1 try:
----> 2     np.array(TestArray())
      3 except:
      4     extype, value, tb = sys.exc_info()
      5     traceback.print_exc()

*** NameError: name 'stop' is not defined


In [5]:
class Parent(object):
    def __init__(self, name):
        self.name = name

    def print_name(self):
        print(self.name)

class Child(Parent):
    def _initialize(self, name):
        super().__init__(name)

    def __init__(self, name):
        self._initialize(name)

Child()._initialize("Ilya")


TypeError: Child.__init__() missing 1 required positional argument: 'name'

In [ ]:
import numpy as np

: 

In [4]:
matrixes = np.random.uniform(size=(100000, 10, 10))
np.linalg.inv(matrixes)

array([[[-2.06877134e+01,  1.60138089e+01, -9.03977810e+00, ...,
         -1.70375074e+00, -9.24534264e+00,  1.31401813e+01],
        [-5.65591440e+00,  3.22907657e+00, -2.81376811e+00, ...,
         -2.63346252e-01, -1.34390023e+00,  5.22298194e+00],
        [ 1.02866430e+02, -8.11967005e+01,  4.78571616e+01, ...,
          1.15471038e+01,  5.03771863e+01, -6.49608535e+01],
        ...,
        [ 9.16990183e+01, -6.96894917e+01,  4.16450398e+01, ...,
          8.70520661e+00,  4.24116535e+01, -5.90244962e+01],
        [-1.43194114e+02,  1.11718344e+02, -6.66695526e+01, ...,
         -1.55662751e+01, -6.91633113e+01,  9.02581120e+01],
        [-4.49410775e+01,  3.24114141e+01, -1.97110684e+01, ...,
         -2.54394244e+00, -1.83529552e+01,  3.00677809e+01]],

       [[ 8.40174309e-01, -3.27268372e-01, -1.12919885e+00, ...,
          7.53766262e-01,  7.66742651e-01, -7.10212929e-01],
        [-8.58029288e-01,  5.48892268e-01,  8.42485675e-03, ...,
         -1.21833951e+00,  4.28954264e

In [19]:
from scipy.special import logsumexp
import numpy as np
import numpy.typing as npt
from scipy.sparse import csr_matrix

In [22]:
def logmatmul(M: npt.NDArray | csr_matrix, log_v: npt.NDArray) -> npt.NDArray[np.complex128]:
    """
    Compute log(M @ v) for a matrix M and a vector v. Output is complex.
    """
    if isinstance(M, np.ndarray):
        log_M = np.log(M + 0j)
    elif isinstance(M, csr_matrix):
        log_M = csr_matrix((np.log(M.data + 0j), M.indices, M.indptr), shape=M.shape)
    else:
        raise ValueError(f"Unsupported matrix type {type(M)}")
    return np.asarray(logsumexp(log_M + log_v, axis=1), dtype=np.complex128)


In [30]:
# make random csr matrix with 0.5 density
M = csr_matrix(np.random.rand(100, 100) < 0.01, dtype=np.float64)
v = np.random.rand(100)
assert np.allclose(M @ v, np.exp(logmatmul(M, np.log(v.astype(np.complex128)))).real)

AssertionError: 

In [38]:
csr_matrix(np.array([[1, 2, 0, 0], [0, 4, 5, 1]])) + np.array([10, 20, 30, 40])

matrix([[11, 22, 30, 40],
        [10, 24, 35, 41]])

In [34]:
np.exp(logmatmul(M, np.log(v.astype(np.complex128)))).real

array([54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52