In [5]:
class Parent(object):
    def __init__(self, name):
        self.name = name

    def print_name(self):
        print(self.name)

class Child(Parent):
    def _initialize(self, name):
        super().__init__(name)

    def __init__(self, name):
        self._initialize(name)

Child()._initialize("Ilya")


TypeError: Child.__init__() missing 1 required positional argument: 'name'

In [ ]:
import numpy as np

: 

In [4]:
matrixes = np.random.uniform(size=(100000, 10, 10))
np.linalg.inv(matrixes)

array([[[-2.06877134e+01,  1.60138089e+01, -9.03977810e+00, ...,
         -1.70375074e+00, -9.24534264e+00,  1.31401813e+01],
        [-5.65591440e+00,  3.22907657e+00, -2.81376811e+00, ...,
         -2.63346252e-01, -1.34390023e+00,  5.22298194e+00],
        [ 1.02866430e+02, -8.11967005e+01,  4.78571616e+01, ...,
          1.15471038e+01,  5.03771863e+01, -6.49608535e+01],
        ...,
        [ 9.16990183e+01, -6.96894917e+01,  4.16450398e+01, ...,
          8.70520661e+00,  4.24116535e+01, -5.90244962e+01],
        [-1.43194114e+02,  1.11718344e+02, -6.66695526e+01, ...,
         -1.55662751e+01, -6.91633113e+01,  9.02581120e+01],
        [-4.49410775e+01,  3.24114141e+01, -1.97110684e+01, ...,
         -2.54394244e+00, -1.83529552e+01,  3.00677809e+01]],

       [[ 8.40174309e-01, -3.27268372e-01, -1.12919885e+00, ...,
          7.53766262e-01,  7.66742651e-01, -7.10212929e-01],
        [-8.58029288e-01,  5.48892268e-01,  8.42485675e-03, ...,
         -1.21833951e+00,  4.28954264e

In [19]:
from scipy.special import logsumexp
import numpy as np
import numpy.typing as npt
from scipy.sparse import csr_matrix

In [22]:
def logmatmul(M: npt.NDArray | csr_matrix, log_v: npt.NDArray) -> npt.NDArray[np.complex128]:
    """
    Compute log(M @ v) for a matrix M and a vector v. Output is complex.
    """
    if isinstance(M, np.ndarray):
        log_M = np.log(M + 0j)
    elif isinstance(M, csr_matrix):
        log_M = csr_matrix((np.log(M.data + 0j), M.indices, M.indptr), shape=M.shape)
    else:
        raise ValueError(f"Unsupported matrix type {type(M)}")
    return np.asarray(logsumexp(log_M + log_v, axis=1), dtype=np.complex128)


In [30]:
# make random csr matrix with 0.5 density
M = csr_matrix(np.random.rand(100, 100) < 0.01, dtype=np.float64)
v = np.random.rand(100)
assert np.allclose(M @ v, np.exp(logmatmul(M, np.log(v.astype(np.complex128)))).real)

AssertionError: 

In [38]:
csr_matrix(np.array([[1, 2, 0, 0], [0, 4, 5, 1]])) + np.array([10, 20, 30, 40])

matrix([[11, 22, 30, 40],
        [10, 24, 35, 41]])

In [34]:
np.exp(logmatmul(M, np.log(v.astype(np.complex128)))).real

array([54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52469308,
       54.52469308, 54.52469308, 54.52469308, 54.52469308, 54.52