In [30]:
import numpy as np
from scipy.linalg import schur
from scipy.spatial.transform import Rotation as R

In [81]:
V = np.array([[1, 0], [0, 1], [0, 0]])
rot_axis = np.array([1, 1, 0])
rotvec = np.pi / 3 * rot_axis / np.linalg.norm(rot_axis)
T = R.from_rotvec(rotvec=rotvec).as_matrix()

In [82]:
np.isclose(T.T , T)

array([[ True,  True, False],
       [ True,  True, False],
       [False, False,  True]])

In [83]:
T @ V

array([[ 0.75      ,  0.25      ],
       [ 0.25      ,  0.75      ],
       [-0.61237244,  0.61237244]])

In [84]:
A = V.T @ T @ V

In [85]:
A

array([[0.75, 0.25],
       [0.25, 0.75]])

In [88]:
M, U = schur(A)

In [89]:
M

array([[1. , 0. ],
       [0. , 0.5]])

In [90]:
U

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [91]:
V @ U

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678],
       [ 0.        ,  0.        ]])

In [92]:
T @ V @ U

array([[ 0.70710678, -0.35355339],
       [ 0.70710678,  0.35355339],
       [ 0.        ,  0.8660254 ]])

In [93]:
V @ U @ M

array([[ 0.70710678, -0.35355339],
       [ 0.70710678,  0.35355339],
       [ 0.        ,  0.        ]])

In [94]:
V.T @ T @ V

array([[0.75, 0.25],
       [0.25, 0.75]])

In [47]:
U @ M @ U.T

array([[0.75, 0.25],
       [0.25, 0.75]])

In [16]:
U

array([[1., 0.],
       [0., 1.]])

In [17]:
V

array([[1, 0],
       [0, 1],
       [0, 0]])

In [18]:
V.T @ T

array([[1, 0, 0],
       [0, 0, 1]])

In [19]:
V @ U

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [95]:
T = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]]).T

In [96]:
T

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [97]:
np.linalg.eig(T)

(array([-0.5+0.8660254j, -0.5-0.8660254j,  1. +0.j       ]),
 array([[ 0.28867513-0.5j,  0.28867513+0.5j, -0.57735027+0.j ],
        [-0.57735027+0.j , -0.57735027-0.j , -0.57735027+0.j ],
        [ 0.28867513+0.5j,  0.28867513-0.5j, -0.57735027+0.j ]]))